# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "clang-format" = super.buildPythonPackage rec {
    pname = "clang-format";
    version = "20.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b8/c2/4892f276102d73df28d71ec42fdfc289feff5677d788230300452f5a728e/clang_format-20.1.0.tar.gz";
      sha256 = "10idy39x366hzh3bb1g7i7gkdwy7s90qzxznn51470ni9i5hjjyw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
